site_name: redhat-taro-7
site_description: 
repo_url: https://github.com/rhdh-skitamura-org/redhat-taro-7-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - redhat-taro-7 Documentation: index.md
